name: publish

on:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Read package.json
        id: package-json
        run: |
          content=`cat ./package.json`
          # the following lines are only required for multi line json
          # content="${content//'%'/'%25'}"
          # content="${content//$'\n'/'%0A'}"
          # content="${content//$'\r'/'%0D'}"
          echo "$changed"
          # end of optional handling for multi line json
          echo "$content"
          echo "packageJson=$content" >> $GITHUB_OUTPUT

      - name: Set env
        env:
          CHANGED: ${{ fromJson(steps.package-json.outputs.packageJson).version != fromJson(steps.package-json.outputs.packageJson).dependencies.naive-ui }}
        run: echo "VERSION_CHANGED=${{env.CHANGED}}" >> $GITHUB_ENV

      - if: env.VERSION_CHANGED == true
        name: Build
        run: |
          pnpm install
          pnpm build

      - if: env.VERSION_CHANGED == true
        name: Update package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: version
          value: ${{ fromJson(steps.package-json.outputs.packageJson).dependencies.naive-ui }}

      - if: env.VERSION_CHANGED == true
        name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "chore: update package version to ${{ fromJson(steps.package-json.outputs.packageJson).dependencies.naive-ui }}"

      - if: env.VERSION_CHANGED == true
        name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.ref }}

      - if: env.VERSION_CHANGED == true
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
